version: '3'

services:
  sonarqube_db:
    image: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    networks:
      - sonarnet
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube
    depends_on:
      - sonarqube_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - sonarnet
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data

  tomcat:
    image: tomcat:9.0
    ports:
      - "8888:8080"
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps

networks:
  sonarnet:

volumes:
  sonarqube_db_data:
  sonarqube_data:
  nexus_data:
  tomcat_webapps:
